error_on_line_overflow = true
error_on_unformatted = true
edition = "2018"
binop_separator = "Front"
condense_wildcard_suffixes = true
fn_single_line = true
where_single_line = true
format_macro_bodies = true
format_macro_matchers = true
merge_imports = true
match_block_trailing_comma = true
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
wrap_comments = true
normalize_doc_attributes = true
