[package]
name = "climate"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
description = "practical command-line interfaces"
license = "GPL-3.0"
homepage = "https://github.com/spacejam/climate"
keywords = ["cli", "commandline", "visualization", "ui"]

[[test]]

name = "test"
path = "test/test.rs"

[dependencies]
termion = "1.1"
quickcheck = "0.3"
log = "0.3"
lazy_static = "0.2"
time = "0.1"
hyper = "0.9"
clippy = "0.0.96"
rust-crypto = "^0.2"
getopts = "0.2"
rsdb = "0.1.0"
protobuf = "1.0"
rand = "0.3"
libc = "0.2"
